- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Installing packages
    package:
      name: "Installing {{ item.name }}"
      state: "State {{ item.state }}"
    loop:
    - { name: "nginx", state: "present" }
    - { name: "git", state: "absent" }
    - { name: "mysql", state: "present" }
