- name: discuss on filter topics
  hosts: local
  connection: local
  vars:
    topics: Linux, Ansible, Shell, Git, AWS
    tagMap:
      name: Ansible
      project: roboshop
      environment: dev
    tagList: [
        {
            "key": "name",
            "value": "Ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "environment",
            "value": "dev"
        }
    ]

  tasks:
  - name: filter topics
    debug: 
      msg: " Topics are: {{ topics | split(',') }}"
    
  - name: default filter
    debug:
      msg: " Hi {{ GREETING | default('Good Morning')}} "
    
  - name: map to list
    debug:
      msg: "{{ tagMap | dict2items }}"

  - name: list to map
    debug:
      msg: "{{ tagList | items2dict }}"