[frontend]
172.31.21.13

[user]
172.31.21.14

[cart]
172.31.21.15

[catalogue]
172.31.21.16

[shipping]
172.31.21.17

[roboshop:children]
frontend
cart
user
catalogue
shipping

[local] ;connection
local ;hosts

[local:vars]
COURSE="Ansible"
TRAINER="Sivakumar"
DURATION="10HRS"
